# roles/httpd/vars/RedHat.yml
---

httpd_packages:
  - hostname  # needed for generating default certificate file
  - httpd
  - mod_ssl
  - openssl   # for ssl self-signed certs generation

httpd_config: /etc/httpd/conf/httpd.conf
httpd_sites_available_dir: /etc/httpd/sites-available
httpd_sites_enabled_dir: /etc/httpd/sites-enabled
httpd_ssl_config: /etc/httpd/conf.d/ssl.conf
httpd_status_config: /etc/httpd/conf.d/status.conf
httpd_01_security_config: /etc/httpd/conf.d/01-security.conf
httpd_02_usability_config: /etc/httpd/conf.d/02-usability.conf
httpd_welcome_config: /etc/httpd/conf.d/welcome.conf
httpd_autoindex_config: /etc/httpd/conf.d/autoindex.conf
httpd_00_base_module: /etc/httpd/conf.modules.d/00-base.conf
httpd_01_cgi_module: /etc/httpd/conf.modules.d/01-cgi.conf

httpd_cert_dir: /etc/pki/tls/certs
httpd_key_dir: /etc/pki/tls/private
