# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
  :otuslinux => {
        :box_name => "centos/7",
        :ip_addr => '192.168.11.106'
  },
}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|

      config.vm.define boxname do |box|

          box.vm.box = boxconfig[:box_name]
          box.vm.host_name = boxname.to_s

          #box.vm.network "forwarded_port", guest: 3260, host: 3260+offset

          box.vm.network "private_network", ip: boxconfig[:ip_addr]

          box.vm.provider :virtualbox do |vb|
            vb.customize ["modifyvm", :id, "--memory", "1024"]
          end

          box.vm.provision "shell", inline: <<-SHELL
			mkdir -p ~root/.ssh
			# TODO before start put your ssh pub key to the target vagrant folder
			# adding my ssh pub key to the root
			#cat /vagrant/ivan.bologov.key.pub >> ~vagrant/.ssh/auth*
			cp ~vagrant/.ssh/auth* ~root/.ssh
			# push hometask to the home dir
			cp -R /vagrant/hometask06 ~vagrant/
			# not necessary
			#yum -y update
			# installing software
			yum install -y epel-release
			yum install -y vim htop mc httpd spawn-fcgi php
			ln -sf /usr/share/zoneinfo/Europe/Moscow /etc/localtime
			systemctl start chronyd.service
			systemctl enable chronyd.service
			# step 1
			systemctl start httpd
			systemctl enable httpd
			cp ~vagrant/hometask06/bloodhound.pl /usr/local/bin/
			chmod +x /usr/local/bin/bloodhound.pl
			#touch /etc/sysconfig/bloodhoundd.conf
			echo "pattern=GET" > /etc/sysconfig/bloodhoundd.conf
			echo "file=/var/log/httpd/access_log" >> /etc/sysconfig/bloodhoundd.conf
			cp ~vagrant/hometask06/bloodhound.service /etc/systemd/system
			systemctl daemon-reload
			systemctl start bloodhound
			# step 2
			mkdir -p /var/run/spawn-fcgi/
			chown apache:apache /var/run/spawn-fcgi
			chmod 775 /var/run/spawn-fcgi
			cp ~vagrant/hometask06/spawn-fcgi /etc/sysconfig/
			cp ~vagrant/hometask06/spawn-fcgi.service /etc/systemd/system
			mv /etc/init.d/spawn-fcgi /etc/init.d/backup-spawn-fcgi
			systemctl daemon-reload
			systemctl start spawn-fcgi.service
			# step 3
			setenforce 0
			cp ~vagrant/hometask06/httpd@.service /etc/systemd/system
			#cp -a /etc/sysconfig/httpd /etc/sysconfig/multiple_httpd
			cp -aR /etc/httpd /etc/httpd_inst01
			cp -aR /etc/httpd /etc/httpd_inst02
			sed -i 's/^Listen 80$/Listen 8081/' /etc/httpd_inst01/conf/httpd.conf
			echo "PidFile /run/httpd/httpd_inst01.pid" >> /etc/httpd_inst01/conf/httpd.conf
			sed -i 's/^Listen 80$/Listen 8082/' /etc/httpd_inst02/conf/httpd.conf
			echo "PidFile /run/httpd/httpd_inst02.pid" >> /etc/httpd_inst02/conf/httpd.conf
			systemctl daemon-reload
			systemctl start httpd@inst01.service
			systemctl start httpd@inst02.service
		  SHELL
      end
  end
end
