# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
  :otuslinux => {
        :box_name => "centos/7",
        :ip_addr => '192.168.11.105'
  },
}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|

      config.vm.define boxname do |box|

          box.vm.box = boxconfig[:box_name]
          box.vm.host_name = boxname.to_s

          #box.vm.network "forwarded_port", guest: 3260, host: 3260+offset

          box.vm.network "private_network", ip: boxconfig[:ip_addr]

          box.vm.provider :virtualbox do |vb|
            vb.customize ["modifyvm", :id, "--memory", "1024"]
          end

          box.vm.provision "shell", inline: <<-SHELL
			mkdir -p ~root/.ssh
			# TODO before start put your ssh pub key to the target vagrant folder
			# adding my ssh pub key to the root
			#cat /vagrant/ivan.bologov.key.pub >> ~vagrant/.ssh/auth*
			cp ~vagrant/.ssh/auth* ~root/.ssh
			# push hometask to the home dir
			cp -R /vagrant/hometask05 ~vagrant/
			chown -R vagrant:vagrant ~vagrant/hometask05
			chmod -R +x ~vagrant/hometask05
			# not necessary
			#yum -y update
			# installing software
			yum install -y epel-release
			yum install -y ssmtp mailx vim ntp htop
			ln -sf /usr/share/zoneinfo/Europe/Moscow /etc/localtime
			ntpdate time.apple.com
			yum remove -y postfix
			cp /vagrant/configs/* /etc/ssmtp/
			crontab -u vagrant -r
			crontab -u vagrant ~vagrant/hometask05/vagrant.cron
		  SHELL
      end
  end
end