# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
  :otuslinux => {
        :box_name => "centos/7",
        :ip_addr => '192.168.11.109'
  },
}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|

      config.vm.define boxname do |box|

          box.vm.box = boxconfig[:box_name]
          box.vm.host_name = boxname.to_s

          #box.vm.network "forwarded_port", guest: 3260, host: 3260+offset

          box.vm.network "private_network", ip: boxconfig[:ip_addr]

          box.vm.provider :virtualbox do |vb|
            vb.customize ["modifyvm", :id, "--memory", "1024"]
          end

          box.vm.provision "shell", inline: <<-SHELL
			mkdir -p ~root/.ssh
	# preparations. not necessary to run
		# before you begin you could put your ssh pub key to the target vagrant folder
		# adding my ssh pub key to the root
			#cat /vagrant/ivan.bologov.key.pub >> ~vagrant/.ssh/auth*
			#cp ~vagrant/.ssh/auth* ~root/.ssh
		# time settings
			#ln -sf /usr/share/zoneinfo/Europe/Moscow /etc/localtime
			#systemctl start chronyd.service
		    #systemctl enable chronyd.service
	# push hometask to the home dir
			cp -R /vagrant/h9p1.py ~vagrant/
			chown -R vagrant:vagrant ~vagrant/h9p1.py
			chmod a+x ~vagrant/h9p1.py
	# installing dependencies
			yum install -y epel-release
			yum -y install python36 python36-setuptools
			python3.6 -m ensurepip
			python3.6 -m pip install --upgrade pip
			python3.6 -m pip install PrettyTable
	#run hometask script. just sample. useless in provision
			#~vagrant/h9p1.py
		  SHELL
      end
  end
end